### PR TITLE
Clean up package build process

### LINKED ISSUE #268: Ensure RCAP has a standard build procedure
Although #267 improved the build with a smaller tarball, RCAP still has a non-standard build procedure where you have to check out the repo, run a script, and then push a release to GitHub.

R has procedures for building packages, so you can run things like:

```
R CMD build rcloud.rcap
```

or

```
R CMD mkdist rcloud.rcap
```

in the parent directory (this is a preferred method to using `devtools`). This will allow sys admins to deploy new versions of RCAP automatically.

### PR DESCRIPTION
**Pull request by useless5771**
Introduced mkdist script that performs steps required to preprocess sources and build RCAP package, FIX #268

### CODE REVIEW

**Comment by shaneporter** [comment]
:1st_place_medal:  @useless5771. Please can you document the options?

The `readme` mentions devtools too; I guess that's still an option, but not the preferred one (and it needs updating on ever up-version). Can we remove it do you think, and add the instructions for this new super-duper build?

Cheers!

**Comment by useless5771** [comment]
Yes, missed out readme file, I will update it.

Thanks

**Comment by useless5771** [comment]
@shaneporter updated the documentation, can you have a look please?

thanks

**Comment by shaneporter** [comment]
Thanks for the doc update @useless5771 
@s-u - are you happy with the build? 

Thanks.

**Comment by shaneporter** [comment]
@gordonwoodhull confirmed in at email that @s-u is happy with the build.

**Pull request merged**
